### ISSUE TITLE
Como usar este plugin?

### ISSUE THREAD

**Issue by israelbolu** [fjcunha/cordova-plugin-pagseguro-plugpag#1]
Como usar este plugin? li o códido é mesmo assim não entendi em como usar com Cordova.

**Comment by fjcunha** [comment]
O plugin ainda está em desenvolvimento, por enquanto está funcionando com Android mas ainda não está em uma versão estável, toda ajuda é bem vinda

**Comment by igortrinidad** [comment]
Opa meu caro, beleza?

Pô, primeiramente parabéns pela iniciativa!

Desenvolvemos um POS usando o plugin da Stone para Cordova para minha hamburgueria e atualmente estou desenvolvendo outras soluções com esse plugin, mas acho que não é muito o foco do pessoal lá dar assistência nesse plugin, ai to procurando outras soluções e lembrei da Pag Seguro...

Esse plugin é para ser usado com as máquinas de pinpad bluetooth ou venda através do gateway?

**Comment by fjcunha** [comment]
Opa, tudo jóia? muito obrigado,
este plugin é para integração com os dispositivos pagseguro (Pinpad, MPRO, MCHIP, etc).
Plugin funcionando apenas para android por enquanto mas transaciona com qualquer dispositivo do pagseguro, segue um app de exemplo em Ionic 3, do plugin em funcionamento.
https://github.com/fjcunha/plugpag-helloworld
Qualquer dúvida só falar.

**Comment by igortrinidad** [comment]
Excelente Fabrício!

Estou testando aqui, como uso Cordova + Vue to apanhei um pouco da estrutura do Ionic haha mas ta indo... 

Cara deixa eu te perguntar, vi aqui que o app tem um método de login no PagSeguro, nesse caso o plugin ou a SDK da PagSeguro pegam os dados do vendedor/conta para efetuar o crédito para seller, correto pois não achei essa info nos parâmetros da transação...

Esse método de login/telas são da lib da PagSeguro ou são do plugin e editáveis?

Você sabe se é viável ou há alguma maneira de passar o código do vendedor ou do cadastro ao invés de haver este login no dispositivo, para deixar o controle mais centralizado?

Tenho uma máquina da Gertec a MOBI-PIN 10 e uma D150 da Stone, vou chegar em casa e testar com as duas num projeto Cordova + Vue que tenho mais familiaridade e te falo como foi :)

**Comment by fjcunha** [comment]
Igor,
seguinte esse login é da lib do pagseguro e não é editável e só é obrigatório para uso do pinpad bluetooth (Minizinha) porque é o modo de ligação no seller e quem faz a transação é o POS/smartphone e não a própria máquina, todos os outros dispositivos fazem a ligação com o seller direto pela máquina que é associada e ativada pela plataforma pagseguro.

Resumindo: se for usar minizinha tem q fazer esse login obrigatóriamente, é da lib deles e isso segundo eles não vai mudar.
Se for usar qualquer outro dispositivo onde as transações são feitas diretamente pelo dispositivo pagseguro (inclusive minizinha CHIP) não precisa desse login e nem passar Id de seller nenhum porque quem faz isso é a máquina deles.
