### ISSUE TITLE
Funcionamento do plugin já está ativo?

### ISSUE THREAD

**Issue by megadrazz** [fjcunha/cordova-plugin-pagseguro-plugpag#2]
mais informações desse plugin?
agradeço!

**Comment by fjcunha** [comment]
Plugin funcionando apenas para android por enquanto mas transaciona com qualquer dispositivo do pagseguro, segue um app de exemplo em Ionic 3, do plugin em funcionamento. 
https://github.com/fjcunha/plugpag-helloworld
Qualquer dúvida só falar.

**Comment by saintclairpcarvalho** [comment]
Fiz um fork do projeto usando a versão 3.1.2 da Api PlugPag do PagSeguro, o resolveu o problema de aparecer a mensagem de "Sem Internet/Verificar Conexão" sempre que se tentava fazer o login no PagSeguro.
https://github.com/saintclairpcarvalho/cordova-plugin-pagseguro-plugpag

**Comment by fjcunha** [comment]
@saintclairpcarvalho bacana demais, faz um pull request que ja atualizo esse repositório também, grato pela colaboração
